api_platform:
    title: KaroRoad API
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    use_symfony_listeners: true
    resource_class_directories:
        - '%kernel.project_dir%/src/Security/ApiResource'
        - '%kernel.project_dir%/src/Task/ApiResource'
        - '%kernel.project_dir%/src/Meet/ApiResource'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
