twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/src/Mailing/Sender/Templates': mailing

when@test:
    twig:
        strict_variables: true
