services:
  karo-road-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - KaroRoadWeb-volume:/var/www/html/storage
    networks:
      - KaroRoadWeb-network
  mysql:
    image: 'mysql:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'KaroRoadWeb123!'
      MYSQL_ROOT_HOST: 'KaroRoadWeb123!'
      MYSQL_DATABASE: 'KaroRoadWeb'
      MYSQL_USER: 'KaroRoadWeb'
      MYSQL_PASSWORD: 'KaroRoadWeb123!'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'KaroRoadWeb-mysql:/var/lib/mysql'
    networks:
      - KaroRoadWeb-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-pKaroRoadWeb123!'
      retries: 3
      timeout: 5s

  mysql_test:
    image: 'mysql:latest'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'KaroRoadWeb123!'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'KaroRoadWebTest'
      MYSQL_USER: 'KaroRoadWeb'
      MYSQL_PASSWORD: 'KaroRoadWeb123!'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'KaroRoadWeb-test-mysql:/var/lib/mysql'
    networks:
      - KaroRoadWeb-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-pKaroRoadWeb123!'
      retries: 3
      timeout: 5s

networks:
  KaroRoadWeb-network:
    driver: bridge
volumes:
  KaroRoadWeb-volume:
    driver: local
  KaroRoadWeb-mysql:
    driver: local
  KaroRoadWeb-test-mysql:
    driver: local